### ISSUE TITLE
Betatester

### ISSUE THREAD

**Issue by ghost** [SnowMB/ProtonetApp#6]
Hi,

so wie ich das hier sehe, ist das eine Desktop Anwendung für die Protonet Chat Funktion?

Eine "ProtoApp_TemporaryKey.pfx" hab ich schon generiert. Leider fehlen mir aber weitere "skills" eine lauffähige Anwendung daraus zu kompilieren.

Könnt ihr mir Hilfestellung geben ?
Ich könnte mich aber auch gerne als Betatester anbieten - und regelmäßig Feedback geben :)

LG
Hannes

**Comment by SnowMB** [comment]
Hallo Hannes,

Das ist mehr oder weniger eine Test-App für mich und meinem Kollegen um UWP-Features und REST-Service Zugriff zu testen. Wir sind weit davon entfernt ein fertiges Produkt zu liefern. Im Moment sind wir auch nur noch sehr sporadisch am weiterentwickeln (je nach Lust und Laune).

Wenn du den existierenden Quellcode selbst benutzen möchtest, kannst du das gerne tun.

Gruß
